name: Pull Request CI Pipeline

# Trigger on pull requests to main branch
on:
  pull_request:
    branches:
      - main # Trigger pipeline on pull requests to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest #Using GitHub hosted runner
    
    steps:
      - name: Login DockerHub
        uses: actions/checkout@v3
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    
      - name: Build the docker image
        run: docker build -t $DOCKER_USERNAME/cicd-pipeline .
    
      - name: Push to docker hub
        run: docker push $DOCKER_USERNAME/cicd-pipeline:latest

      - name: Pull docker image
        run: docker pull $DOCKER_USERNAME/cicd-pipeline:latest

      - name: Run docker container
        run: docker run -d -p 8080:8000 --name cicd-pipeline-container $DOCKER_USERNAME/cicd-pipeline
