name: CI Pipeline
on:
  push_request:
  branches: [ "main" ]
  
  pull_request:
  branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest #Using GitHub hosted runner
    
  steps:
  - users: actions/checkout@v3
  - name: Login DockerHub
  - env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    
  - name: Build the docker image
    run: docker build -t mohasinmaner/pocket-contacts-pro .
    
  - name: Push to docker hub
    run: docker push mohasinmaner/pocket-contacts-pro:latest
    
    
    
    
